name: Release

on:
  release:
    types: published
    tags: v*.*.*

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }} Tag ${{ github.event.release.tag_name }}'"
